using System.Collections.Generic;

namespace EasyLayout.Droid.Sample.Models
{
    public static class Data
    {
        public static List<Product> GetProducts()
        {
            return new List<Product>
            {
                new Product { Id = 1, Title = "Chai", Amount = 18.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 2, Title = "Chang", Amount = 19.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 3, Title = "Aniseed Syrup", Amount = 10.00M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 4, Title = "Chef Anton's Cajun Seasoning", Amount = 22.00M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 5, Title = "Chef Anton's Gumbo Mix", Amount = 21.35M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 6, Title = "Grandma's Boysenberry Spread", Amount = 25.00M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 7, Title = "Uncle Bob's Organic Dried Pears", Amount = 30.00M, CategoryId = 7, Category = "Produce" },
                new Product { Id = 8, Title = "Northwoods Cranberry Sauce", Amount = 40.00M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 9, Title = "Mishi Kobe Niku", Amount = 97.00M, CategoryId = 6, Category = "Meat/Poultry" },
                new Product { Id = 10, Title = "Ikura", Amount = 31.00M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 11, Title = "Queso Cabrales", Amount = 21.00M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 12, Title = "Queso Manchego La Pastora", Amount = 38.00M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 13, Title = "Konbu", Amount = 6.00M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 14, Title = "Tofu", Amount = 23.25M, CategoryId = 7, Category = "Produce" },
                new Product { Id = 15, Title = "Genen Shouyu", Amount = 15.50M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 16, Title = "Pavlova", Amount = 17.45M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 17, Title = "Alice Mutton", Amount = 39.00M, CategoryId = 6, Category = "Meat/Poultry" },
                new Product { Id = 18, Title = "Carnarvon Tigers", Amount = 62.50M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 19, Title = "Teatime Chocolate Biscuits", Amount = 9.20M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 20, Title = "Sir Rodney's Marmalade", Amount = 81.00M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 21, Title = "Sir Rodney's Scones", Amount = 10.00M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 22, Title = "Gustaf's Knäckebröd", Amount = 21.00M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 23, Title = "Tunnbröd", Amount = 9.00M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 24, Title = "Guaraná Fantástica", Amount = 4.50M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 25, Title = "NuNuCa Nuß-Nougat-Creme", Amount = 14.00M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 26, Title = "Gumbär Gummibärchen", Amount = 31.23M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 27, Title = "Schoggi Schokolade", Amount = 43.90M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 28, Title = "Rössle Sauerkraut", Amount = 45.60M, CategoryId = 7, Category = "Produce" },
                new Product { Id = 29, Title = "Thüringer Rostbratwurst", Amount = 123.79M, CategoryId = 6, Category = "Meat/Poultry" },
                new Product { Id = 30, Title = "Nord-Ost Matjeshering", Amount = 25.89M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 31, Title = "Gorgonzola Telino", Amount = 12.50M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 32, Title = "Mascarpone Fabioli", Amount = 32.00M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 33, Title = "Geitost", Amount = 2.50M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 34, Title = "Sasquatch Ale", Amount = 14.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 35, Title = "Steeleye Stout", Amount = 18.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 36, Title = "Inlagd Sill", Amount = 19.00M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 37, Title = "Gravad lax", Amount = 26.00M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 38, Title = "Côte de Blaye", Amount = 263.50M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 39, Title = "Chartreuse verte", Amount = 18.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 40, Title = "Boston Crab Meat", Amount = 18.40M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 41, Title = "Jack's New England Clam Chowder", Amount = 9.65M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 42, Title = "Singaporean Hokkien Fried Mee", Amount = 14.00M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 43, Title = "Ipoh Coffee", Amount = 46.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 44, Title = "Gula Malacca", Amount = 19.45M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 45, Title = "Rogede sild", Amount = 9.50M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 46, Title = "Spegesild", Amount = 12.00M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 47, Title = "Zaanse koeken", Amount = 9.50M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 48, Title = "Chocolade", Amount = 12.75M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 49, Title = "Maxilaku", Amount = 20.00M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 50, Title = "Valkoinen suklaa", Amount = 16.25M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 51, Title = "Manjimup Dried Apples", Amount = 53.00M, CategoryId = 7, Category = "Produce" },
                new Product { Id = 52, Title = "Filo Mix", Amount = 7.00M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 53, Title = "Perth Pasties", Amount = 32.80M, CategoryId = 6, Category = "Meat/Poultry" },
                new Product { Id = 54, Title = "Tourtière", Amount = 7.45M, CategoryId = 6, Category = "Meat/Poultry" },
                new Product { Id = 55, Title = "Pâté chinois", Amount = 24.00M, CategoryId = 6, Category = "Meat/Poultry" },
                new Product { Id = 56, Title = "Gnocchi di nonna Alice", Amount = 38.00M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 57, Title = "Ravioli Angelo", Amount = 19.50M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 58, Title = "Escargots de Bourgogne", Amount = 13.25M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 59, Title = "Raclette Courdavault", Amount = 55.00M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 60, Title = "Camembert Pierrot", Amount = 34.00M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 61, Title = "Sirop d'érable", Amount = 28.50M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 62, Title = "Tarte au sucre", Amount = 49.30M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 63, Title = "Vegie-spread", Amount = 43.90M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 64, Title = "Wimmers gute Semmelknödel", Amount = 33.25M, CategoryId = 5, Category = "Grains/Cereals" },
                new Product { Id = 65, Title = "Louisiana Fiery Hot Pepper Sauce", Amount = 21.05M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 66, Title = "Louisiana Hot Spiced Okra", Amount = 17.00M, CategoryId = 2, Category = "Condiments" },
                new Product { Id = 67, Title = "Laughing Lumberjack Lager", Amount = 14.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 68, Title = "Scottish Longbreads", Amount = 12.50M, CategoryId = 3, Category = "Confections" },
                new Product { Id = 69, Title = "Gudbrandsdalsost", Amount = 36.00M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 70, Title = "Outback Lager", Amount = 15.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 71, Title = "Flotemysost", Amount = 21.50M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 72, Title = "Mozzarella di Giovanni", Amount = 34.80M, CategoryId = 4, Category = "Dairy Products" },
                new Product { Id = 73, Title = "Röd Kaviar", Amount = 15.00M, CategoryId = 8, Category = "Seafood" },
                new Product { Id = 74, Title = "Longlife Tofu", Amount = 10.00M, CategoryId = 7, Category = "Produce" },
                new Product { Id = 75, Title = "Rhönbräu Klosterbier", Amount = 7.75M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 76, Title = "Lakkalikööri", Amount = 18.00M, CategoryId = 1, Category = "Beverages" },
                new Product { Id = 77, Title = "Original Frankfurter grüne Soße", Amount = 13.00M, CategoryId = 2, Category = "Condiments" },
            };
        }
    }
}